// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrestationApi.Models;

namespace PrestationApi.Migrations
{
    [DbContext(typeof(PrestationDbContext))]
    [Migration("20181221201939_Alter-CodeChantier-CreationDate")]
    partial class AlterCodeChantierCreationDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("PrestationApi.Models.CodeChantier", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.HasKey("Code");

                    b.ToTable("CodesChantier");
                });
#pragma warning restore 612, 618
        }
    }
}
